global Palette  {
    out property <color> window-background: #eee;
    out property <color> widget-background: #ddd;
    out property <color> widget-stroke: #888;
    out property <color> window-border: #ccc;
    out property <color> text-color: #666;
    out property <color> hyper-blue: #90d1ff;

}

component Label inherits Text {
    color: Palette.text-color;
}

export component RadioButton inherits TouchArea {
    in property text <=> t.text;
    in-out property <bool> checked;

    HorizontalLayout {
        spacing: 5px;

        VerticalLayout {
            alignment: center;

            Rectangle {
                width: 20px;
                height: 20px;
                border-width: 1.5px;
                border-color: root.has-hover ? Palette.widget-stroke : transparent;
                border-radius: self.width / 2;
                background: root.pressed ? Palette.widget-background.darker(30%) : Palette.widget-background;

                if root.checked : Rectangle {
                    background: root.has-hover ? Palette.widget-stroke.darker(100%) : Palette.widget-stroke;
                    border-radius: self.width / 2;
                    width: parent.width / 2;
                    height: parent.width / 2;
                    x: parent.width / 4;
                    y: parent.width / 4;
                }
            }
        }

        t := Label {

        }
    }
}
