import { VerticalBox } from "std-widgets.slint";
export component AbstractWindows inherits Window {
    // no-frame: true;
    padding: 0;

    VerticalBox {
        padding: 0;
        height: 200px;
        y: 0;

        Rectangle {
            height: 100px;
            padding: 10px;
            background: #f00;
            Text {
                text: "Title";
            }
        }
    }
}