import { Button, VerticalBox, HorizontalBox, LineEdit, CheckBox, GroupBox, ComboBox, GridBox, TextEdit } from "std-widgets.slint";
import { AbstractWindows } from "abstractwindows.slint";
import { RadioButton } from "widgets/radiobutton.slint";

export component SimpleWindows inherits AbstractWindows {
    title: "Filemer";

    in-out property<int> counter: 42;
    callback request-increase-value();

    height: 480px;
    width: 600px;

    VerticalBox {

        HorizontalBox {
            VerticalBox {
                // Folder tree
                visible: false;
            }
            VerticalBox {
                y: 100px;

                HorizontalBox {
                    LineEdit {
                        text: "test";
                        height: 60px;
                    }
                    Button {
                        text: @tr("Browse");
                        clicked => {
                        }
                    }

                }

                GroupBox {
                    title: @tr("Options");
                    height: 150px;
                    width: 50%;

                    Rectangle {
                        VerticalLayout {
                            CheckBox { text: @tr("Convert characters Unicode to ASCII"); checked: true ;}
                            CheckBox { text: @tr("Apply for files in sub directory"); }
                            CheckBox {
                                text: @tr("Apply for directory");
                                accessible-value: "apply for directory";
                            }
                            CheckBox {
                                text: @tr("Remove special characters");
                                accessible-value: "remove_special_characters";
                            }
                        }
                    }
                }

                GroupBox {
                    title: @tr("Text transform");
                    height: 50px;

                    HorizontalBox {
                        RadioButton {
                            text: @tr("Do nothing");
                        }
                        RadioButton {
                            text: @tr("Capitalize first letter");
                            checked: true;
                        }
                        RadioButton {
                            text: @tr("Uppercase all letters");
                        }
                        RadioButton {
                            text: @tr("Lowercase all letters");
                        }
                    }
                }

                GroupBox {
                    title: @tr("Replaces");

                        HorizontalBox {
                            Text {
                                text: @tr("Find");
                            }
                            LineEdit {
                            }
                        }
                        HorizontalBox {
                            Text {
                                text: "Replace";
                            }
                            LineEdit {
                            }
                        }
                }

                GroupBox {
                    // image features
                    visible: false;
                }
            }



            VerticalBox {
                // logs
                visible: false;

                HorizontalBox {
                    TouchArea {
                        height: 30px;
                        width: 30px;
                    }

                    TextEdit {
                        width: 100%;
                    }
                }

                TextEdit {

                }
            }
        }

        HorizontalBox {
            Button {
                text: @tr("Start");
            }
        }
    }
}
